export const SET_USER = 'SET_USER'

export const SET_BOOK = 'SET_BOOK'

export const SET_SHOWDETAIL = 'SET_SHOWDETAIL'

export const SET_SHELF = 'SET_SHELF'

export const SET_RECOMMENDLIST = 'SET_RECOMMENDLIST'

export const SET_RANKLIST = 'SET_RANKLIST'

export const SET_SEARCHHISTORY = 'SET_SEARCHHISTORY'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'
